# Generated by Django 6.1 on 2026-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_order_location_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
