# Generated by Django 6.1 on 2026-08-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_order_location_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_lat',
            field=models.CharField(blank=True, max_length=50, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_lng',
            field=models.CharField(blank=True, max_length=50, verbose_name='Долгота'),
        ),
    ]
